fix: Don't abort an install if a dangling tracking link exists
Every once in a while a user runs `brew install --overwrite FORMULA` and gets the error
```
Error: No such file or directory - /opt/homebrew/var/homebrew/linked/sq-satoolbox
```

The error is raised from [Library/Homebrew/keg.rb:105](https://github.com/Homebrew/brew/blob/51b612b63b86fbb0fe4ee39b8756c7fb05d4e964/Library/Homebrew/keg.rb#L105) which is in a call stack trying to tell you that the formula is already linked.

But I'm suggesting we should not consider it be linked when the symlink is dangling. `brew install` will [remediate the situation correectly](https://github.com/Homebrew/brew/blob/51b612b63b86fbb0fe4ee39b8756c7fb05d4e964/Library/Homebrew/formula_installer.rb#L1161-L1164) anyway.